"""Register each workstation's LLM key as a LiteLLM virtual key bound to its employee.

The key values are generated by ./console.sh into .env and handed to exactly one
workstation each; this makes LiteLLM accept them and attribute usage to that person.
Idempotent: an existing key is left as it is. Standard library only (runs in the
workstation image, which carries no Python packages).
"""
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

URL = os.environ["LITELLM_URL"].rstrip("/")
MASTER = os.environ.get("LITELLM_MASTER_KEY", "")
MODELS = [m for m in os.environ.get("LLM_KEY_MODELS", "bob-assistant").split(",") if m]


def call(path: str, body: dict | None = None) -> tuple[int, str]:
    request = urllib.request.Request(f"{URL}{path}", headers={"Authorization": f"Bearer {MASTER}",
                                                              "Content-Type": "application/json"},
                                     data=json.dumps(body).encode() if body is not None else None)
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            return response.status, response.read().decode()
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read().decode()


def main() -> int:
    if not MASTER:
        print("[llm-provision] LITELLM_MASTER_KEY가 없어 건너뜁니다.")
        return 0
    for _ in range(60):
        try:
            if call("/health/liveliness")[0] == 200:
                break
        except OSError:
            pass
        time.sleep(2)
    for item in (part.strip() for part in os.environ.get("LLM_KEYS", "").split(",")):
        if not item:
            continue
        workstation, email, key = (item.split("=", 2) + ["", ""])[:3]
        if not key:
            print(f"[llm-provision] {workstation}: 키가 비어 있어 건너뜁니다.")
            continue
        if call("/key/info?" + urllib.parse.urlencode({"key": key}))[0] == 200:
            print(f"[llm-provision] {workstation}: 이미 등록됨")
            continue
        status, text = call("/key/generate", {
            "key": key, "user_id": email, "key_alias": workstation, "models": MODELS,
            "metadata": {"workstation": workstation, "employee": email},
            "max_parallel_requests": 2, "rpm_limit": 30})
        if status >= 300:
            print(f"[llm-provision] {workstation}: 실패 HTTP {status} {text[:200]}", file=sys.stderr)
            return 1
        print(f"[llm-provision] {workstation}: {email} 전용 키 등록")
    return 0


if __name__ == "__main__":
    sys.exit(main())
