"""Register each workstation's LLM key as a LiteLLM virtual key bound to its employee.

The key values are generated by ./console.sh into .env and handed to exactly one
workstation each; this makes LiteLLM accept them and attribute usage to that person.
Idempotent: an existing key is left as it is.
"""
import os
import sys
import time

import httpx

URL = os.environ["LITELLM_URL"].rstrip("/")
MASTER = os.environ.get("LITELLM_MASTER_KEY", "")


def main() -> int:
    if not MASTER:
        print("[llm-provision] LITELLM_MASTER_KEY가 없어 건너뜁니다.")
        return 0
    headers = {"Authorization": f"Bearer {MASTER}"}
    for _ in range(60):
        try:
            if httpx.get(f"{URL}/health/liveliness", timeout=3).status_code == 200:
                break
        except httpx.HTTPError:
            pass
        time.sleep(2)
    for item in (part.strip() for part in os.environ.get("LLM_KEYS", "").split(",")):
        if not item:
            continue
        workstation, email, key = (item.split("=", 2) + ["", ""])[:3]
        if not key:
            print(f"[llm-provision] {workstation}: 키가 비어 있어 건너뜁니다.")
            continue
        info = httpx.get(f"{URL}/key/info", params={"key": key}, headers=headers, timeout=10)
        if info.status_code == 200:
            print(f"[llm-provision] {workstation}: 이미 등록됨")
            continue
        response = httpx.post(f"{URL}/key/generate", headers=headers, timeout=20, json={
            "key": key, "user_id": email, "key_alias": workstation, "models": ["bob-assistant"],
            "metadata": {"workstation": workstation, "employee": email},
            "max_parallel_requests": 2, "rpm_limit": 30})
        if response.status_code >= 300:
            print(f"[llm-provision] {workstation}: 실패 HTTP {response.status_code} {response.text[:200]}", file=sys.stderr)
            return 1
        print(f"[llm-provision] {workstation}: {email} 전용 키 등록")
    return 0


if __name__ == "__main__":
    sys.exit(main())
